version: '3'
services:
  postgres_db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: akhil
      POSTGRES_PASSWORD: akhil123
      POSTGRES_DB: testdb
  webapp:
    image: node:14
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://akhil:akhil123@postgres_db:5432/testdb
    depends_on:
      - postgres_db
volumes: 
  postgres-data:
